### ISSUE TITLE
Package not found in NPM

### ISSUE THREAD

**Issue by jeffward01** [osiro/netscape-cookies-exporter#1]
![image](https://user-images.githubusercontent.com/12589359/153941329-48fa4942-b3f6-4034-ae2c-04cd63bc01bd.png)

I ran:

````bash
> npm install https://github.com/osiro/netscape-cookies-exporter.git
````

And this did install it.. however I could not run it

**Comment by osiro** [comment]
Sorry, I got the incorrect package name in the README.

Fixed!
