### ISSUE TITLE
Files named "netscape-cookier-exporter" instead of "netscape-cookies-exporter"

### ISSUE THREAD

**Issue by mrnngbgs** [osiro/netscape-cookies-exporter#2]
Hi, the files in the Roaming folder have a typo in them - "cookier" instead of "cookies". Just wanted to let everyone know! So if you want to get the script to run just type the following instead of what it says in the "usage" section:

netscape-cookier-exporter -u https://google.com -o cookies.txt

**Comment by osiro** [comment]
Thanks @mrnngbgs! 

I've fixed the issue and released the new version to [npm](https://www.npmjs.com/package/netscape-cookies-exporter/v/1.1.1).
